baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "01-02-2006"
  dateformNumTime = "01-02-2006 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Fabian Latorre"
  keywords = "academia, mathematics, machine learning, phd, epfl"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "articles"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Fabian Latorre"
    homeSubtitle = "PhD Student @EPFL Lausanne, Switzerland."
    keywords = ""
    copyright = "All rights reversed"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "fabian_latorre/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

# Social links
[[params.social]]
    name = "github"
    url = "https://github.com/latorrefabian/"
[[params.social]]
    name = "twitter"
    url = "https://twitter.com/fabianlat/"


# And you can even create generic menu
[menu]
#   [[menu.main]]
#     identifier = "about"
#     name       = "About"
#     url        = "/about"
  [[menu.main]]
    identifier = "research"
    name       = "Research"
    url        = "/publications"
